services:
  - type: web
    name: rog-store
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: APP_NAME
        value: "ROG Store"
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "true"
      - key: APP_KEY
        value: "base64:cjh0b296V1ZlMnhuTXRwbjR0UG9mY1VpdmNYeEVmRnc="
      - key: APP_URL
        value: https://rog-store.onrender.com
      - key: LOG_LEVEL
        value: debug
      - key: SESSION_DRIVER
        value: file
      - key: SESSION_LIFETIME
        value: "120"
      - key: SESSION_SECURE_COOKIE
        value: "false"
      - key: CACHE_STORE
        value: file
      - key: BAKONG_API_URL
        value: https://api-bakong.nbc.gov.kh
      - key: BAKONG_ACCOUNT_ID
        sync: false
      - key: BAKONG_MERCHANT_NAME
        sync: false
      - key: BAKONG_MERCHANT_CITY
        sync: false
      - key: BAKONG_TOKEN
        sync: false
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false
      - key: DATABASE_URL
        sync: false
